// LoL Draft Assistant dataset — Patch 26.12 (June 12, 2026)
// Sources: OP.GG Emerald+ solo queue (4.68M matches), gol.gg 2026 pro season pick/ban,
// patch 26.12 official notes. Numbers are snapshots; refresh on new patches.
//
// Per-champion fields:
//  roles: { role: {wr, pr, tier} }  — solo queue win rate %, pick rate %, tier
//  pro: {p: presence% (picks+bans), wr: pro win rate %}  — 0 presence = not pro-relevant
//  flex: roles seen in pro/competitive (2+ → flex pick value)
//  dmg: "ad" | "ap" | "mix"
//  a: attributes 0–3 — cc, engage, front(line), poke, split(push), early, late, peel, wave(clear)
//  counteredBy / beats: directional matchups in primary role
//  syn: champions this pairs well with (any role)
//  blind: safe to blind-pick in primary role

const PATCH = "26.12";
const DATA_UPDATED = "2026-06-12";
const DDRAGON_FALLBACK = "16.12.1";

const ROLES = ["top", "jungle", "mid", "adc", "support"];
const ROLE_LABEL = { top: "Top", jungle: "Jungle", mid: "Mid", adc: "ADC", support: "Support" };
const ROLE_ICON = { top: "⛰", jungle: "🌲", mid: "✦", adc: "🏹", support: "🛡" };

const CHAMPIONS = {
  // ============ TOP ============
  "Aatrox":      { id:"Aatrox", roles:{top:{wr:50.4,pr:6.9,tier:"A"},jungle:{wr:50.9,pr:2.0,tier:"A"}}, pro:{p:18,wr:50}, flex:["top"], dmg:"ad", a:{cc:2,engage:1,front:2,poke:0,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["Fiora","Olaf","Vayne","Kled"], beats:["Gnar","Ornn","KSante","Malphite"], syn:["Orianna","Vi"], blind:true },
  "Garen":       { id:"Garen", roles:{top:{wr:51.6,pr:8.0,tier:"S"}}, pro:{p:2,wr:48}, flex:["top"], dmg:"mix", a:{cc:1,engage:1,front:2,poke:0,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["Vayne","Quinn","Teemo","Kayle"], beats:["Yasuo","Tryndamere","Riven","Irelia"], syn:["Lux","Yuumi"], blind:true },
  "Malphite":    { id:"Malphite", roles:{top:{wr:51.0,pr:7.0,tier:"S"}}, pro:{p:6,wr:49}, flex:["top","mid","support"], dmg:"ap", a:{cc:3,engage:3,front:3,poke:1,split:0,early:1,late:2,peel:1,wave:1}, counteredBy:["Vayne","Fiora","DrMundo","Yorick"], beats:["Jax","Yone","Irelia","Tryndamere","Riven"], syn:["Yasuo","Yone","Katarina","MissFortune"], blind:false },
  "Ornn":        { id:"Ornn", roles:{top:{wr:51.4,pr:4.1,tier:"S"}}, pro:{p:10,wr:48}, flex:["top"], dmg:"mix", a:{cc:3,engage:3,front:3,poke:0,split:0,early:1,late:3,peel:2,wave:2}, counteredBy:["Vayne","Gwen","Fiora","Darius"], beats:["Gangplank","Kayle","Yone","Aurora"], syn:["Jinx","Aphelios","Azir"], blind:true },
  "Jax":         { id:"Jax", roles:{top:{wr:50.4,pr:6.2,tier:"A"},jungle:{wr:49.8,pr:1.5,tier:"B"}}, pro:{p:8,wr:50}, flex:["top","jungle"], dmg:"mix", a:{cc:1,engage:1,front:2,poke:0,split:3,early:1,late:3,peel:0,wave:1}, counteredBy:["Malphite","Gnar","Quinn","Poppy"], beats:["Camille","Irelia","Tryndamere","Viego"], syn:["Orianna","Shen"], blind:true },
  "Yone":        { id:"Yone", roles:{top:{wr:50.1,pr:7.0,tier:"A"},mid:{wr:48.4,pr:5.9,tier:"B"}}, pro:{p:7,wr:49}, flex:["top","mid"], dmg:"mix", a:{cc:2,engage:2,front:0,poke:0,split:2,early:1,late:3,peel:0,wave:2}, counteredBy:["Malphite","Pantheon","Aatrox","Akshan"], beats:["Gwen","Kayle","Vladimir","Ryze"], syn:["Malphite","Alistar","Diana","Orianna"], blind:false },
  "Tryndamere":  { id:"Tryndamere", roles:{top:{wr:51.8,pr:3.0,tier:"A"}}, pro:{p:1,wr:50}, flex:["top"], dmg:"ad", a:{cc:1,engage:1,front:0,poke:0,split:3,early:2,late:3,peel:0,wave:2}, counteredBy:["Malphite","Garen","Teemo","Jax"], beats:["Kayle","Gangplank","Ryze"], syn:["Shen","Twisted Fate"], blind:false },
  "Sion":        { id:"Sion", roles:{top:{wr:50.4,pr:5.9,tier:"A"}}, pro:{p:31,wr:49}, flex:["top"], dmg:"mix", a:{cc:3,engage:2,front:3,poke:1,split:2,early:1,late:2,peel:1,wave:3}, counteredBy:["Vayne","Gwen","Fiora","Darius"], beats:["Malphite","Ornn","KSante","Cassiopeia"], syn:["Senna","Caitlyn"], blind:true },
  "Sett":        { id:"Sett", roles:{top:{wr:50.6,pr:4.7,tier:"A"}}, pro:{p:4,wr:49}, flex:["top","support"], dmg:"ad", a:{cc:2,engage:2,front:3,poke:0,split:2,early:2,late:1,peel:1,wave:1}, counteredBy:["Vayne","Gnar","Teemo","Kayle"], beats:["Irelia","Aatrox","Yone","KSante"], syn:["Yasuo","Orianna"], blind:true },
  "Shen":        { id:"Shen", roles:{top:{wr:51.1,pr:3.7,tier:"S"}}, pro:{p:5,wr:51}, flex:["top","support"], dmg:"mix", a:{cc:2,engage:1,front:3,poke:0,split:2,early:1,late:2,peel:3,wave:1}, counteredBy:["Gwen","Darius","Mordekaiser","Illaoi"], beats:["Riven","Akali","Camille"], syn:["Twitch","Kaisa","Tryndamere"], blind:true },
  "Gangplank":   { id:"Gangplank", roles:{top:{wr:50.3,pr:5.2,tier:"A"}}, pro:{p:4,wr:50}, flex:["top"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:2,split:2,early:1,late:3,peel:1,wave:2}, counteredBy:["Irelia","Renekton","Pantheon","Sett"], beats:["Kayle","Ornn","Sion","Nasus"], syn:["Orianna","Azir","Caitlyn"], blind:false },
  "Darius":      { id:"Darius", roles:{top:{wr:49.8,pr:6.5,tier:"A"}}, pro:{p:3,wr:47}, flex:["top"], dmg:"ad", a:{cc:2,engage:1,front:2,poke:0,split:2,early:3,late:1,peel:0,wave:1}, counteredBy:["Vayne","Quinn","Kayle","Gnar"], beats:["Ornn","Sion","Shen","Aatrox","KSante"], syn:["Nocturne","TwistedFate"], blind:false },
  "Kayle":       { id:"Kayle", roles:{top:{wr:51.6,pr:2.6,tier:"A"}}, pro:{p:1,wr:50}, flex:["top","mid"], dmg:"mix", a:{cc:1,engage:0,front:0,poke:1,split:2,early:0,late:3,peel:2,wave:2}, counteredBy:["Darius","Irelia","Riven","Tryndamere"], beats:["Sion","Nasus","Malphite"], syn:["Jax","MasterYi","Kindred"], blind:false },
  "Olaf":        { id:"Olaf", roles:{top:{wr:51.6,pr:2.5,tier:"A"},jungle:{wr:49.5,pr:1.2,tier:"B"}}, pro:{p:3,wr:49}, flex:["top","jungle"], dmg:"ad", a:{cc:1,engage:2,front:2,poke:0,split:1,early:3,late:1,peel:0,wave:2}, counteredBy:["Teemo","Vayne","Kayle","Quinn"], beats:["Aatrox","Irelia","Riven","Gwen"], syn:["Orianna","Lulu"], blind:false },
  "Urgot":       { id:"Urgot", roles:{top:{wr:51.7,pr:2.2,tier:"A"}}, pro:{p:1,wr:49}, flex:["top"], dmg:"ad", a:{cc:2,engage:1,front:2,poke:1,split:2,early:2,late:2,peel:1,wave:2}, counteredBy:["Vayne","Kayle","Gwen","Olaf"], beats:["Aatrox","Darius","Sett","Irelia"], syn:["Senna","Lulu"], blind:true },
  "Singed":      { id:"Singed", roles:{top:{wr:51.4,pr:2.6,tier:"A"}}, pro:{p:1,wr:48}, flex:["top"], dmg:"ap", a:{cc:2,engage:2,front:2,poke:0,split:3,early:1,late:2,peel:1,wave:3}, counteredBy:["Teemo","Cassiopeia","Vayne"], beats:["Yorick","Nasus","Tryndamere"], syn:["Zilean","TwistedFate"], blind:true },
  "Riven":       { id:"Riven", roles:{top:{wr:50.6,pr:3.4,tier:"A"}}, pro:{p:2,wr:49}, flex:["top"], dmg:"ad", a:{cc:2,engage:2,front:0,poke:0,split:2,early:2,late:2,peel:0,wave:1}, counteredBy:["Garen","Poppy","Malphite","Renekton"], beats:["Kayle","Gwen","Vladimir","Cassiopeia"], syn:["Yasuo","Diana"], blind:false },
  "Teemo":       { id:"Teemo", roles:{top:{wr:49.9,pr:4.2,tier:"B"},adc:{wr:52.8,pr:0.8,tier:"A"}}, pro:{p:1,wr:46}, flex:["top"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:2,split:2,early:2,late:1,peel:0,wave:1}, counteredBy:["Irelia","Yone","Sylas","DrMundo"], beats:["Darius","Garen","Olaf","Singed","Tryndamere"], syn:["Caitlyn","Zyra"], blind:false },
  "Illaoi":      { id:"Illaoi", roles:{top:{wr:50.9,pr:2.5,tier:"A"}}, pro:{p:1,wr:47}, flex:["top"], dmg:"ad", a:{cc:1,engage:0,front:2,poke:1,split:3,early:2,late:2,peel:0,wave:2}, counteredBy:["Vayne","Kayle","Gnar","Teemo"], beats:["Shen","Sion","Ornn","Garen"], syn:["Orianna","Nautilus"], blind:false },
  "Camille":     { id:"Camille", roles:{top:{wr:50.7,pr:2.7,tier:"A"}}, pro:{p:5,wr:50}, flex:["top","support"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:0,split:3,early:1,late:3,peel:0,wave:1}, counteredBy:["Jax","Malphite","Poppy","Illaoi"], beats:["Gwen","Vladimir","Kayle","Ryze"], syn:["Galio","TwistedFate"], blind:false },
  "Irelia":      { id:"Irelia", roles:{top:{wr:49.6,pr:4.4,tier:"B"},mid:{wr:49.3,pr:3.3,tier:"A"}}, pro:{p:6,wr:48}, flex:["top","mid"], dmg:"mix", a:{cc:2,engage:2,front:1,poke:0,split:2,early:2,late:2,peel:0,wave:3}, counteredBy:["Olaf","Sett","Garen","Pantheon","Renekton"], beats:["Teemo","Kayle","Gangplank","Azir"], syn:["Orianna","Nautilus"], blind:false },
  "DrMundo":     { id:"DrMundo", name:"Dr. Mundo", roles:{top:{wr:50.1,pr:3.6,tier:"A"}}, pro:{p:2,wr:49}, flex:["top"], dmg:"mix", a:{cc:1,engage:1,front:3,poke:1,split:2,early:0,late:3,peel:0,wave:2}, counteredBy:["Vayne","Gwen","Fiora","Kayle"], beats:["Malphite","Teemo","Aatrox","Sion"], syn:["Jinx","Aphelios"], blind:true },
  "Jayce":       { id:"Jayce", roles:{top:{wr:49.1,pr:5.8,tier:"B"},mid:{wr:49.0,pr:1.8,tier:"B"}}, pro:{p:34,wr:49}, flex:["top","mid"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:3,split:1,early:2,late:2,peel:1,wave:2}, counteredBy:["Irelia","Wukong","Renekton","Yone"], beats:["Gnar","KSante","Ornn","Sion"], syn:["Karma","Ashe","Varus"], blind:false },
  "Heimerdinger":{ id:"Heimerdinger", roles:{top:{wr:51.7,pr:1.2,tier:"A"}}, pro:{p:1,wr:48}, flex:["top","support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:2,split:1,early:2,late:2,peel:1,wave:3}, counteredBy:["Irelia","Sylas","Yone"], beats:["Nasus","Sion","Urgot","Darius"], syn:["Jhin","Caitlyn"], blind:false },
  "KSante":      { id:"KSante", name:"K'Sante", roles:{top:{wr:48.8,pr:5.5,tier:"B"}}, pro:{p:26,wr:43}, flex:["top"], dmg:"mix", a:{cc:3,engage:2,front:3,poke:0,split:1,early:1,late:2,peel:2,wave:1}, counteredBy:["Darius","Aatrox","Sion","Illaoi"], beats:["Gnar","Jayce","Renekton"], syn:["Orianna","Azir","Aphelios"], blind:true },
  "Gwen":        { id:"Gwen", roles:{top:{wr:50.3,pr:2.5,tier:"A"}}, pro:{p:18,wr:57}, flex:["top"], dmg:"ap", a:{cc:1,engage:1,front:1,poke:0,split:3,early:1,late:3,peel:0,wave:2}, counteredBy:["Olaf","Riven","Sett","Renekton"], beats:["Ornn","Sion","DrMundo","Malphite","KSante"], syn:["Vi","Orianna"], blind:false },
  "Zaahen":      { id:"Zaahen", roles:{top:{wr:49.9,pr:3.0,tier:"B"}}, pro:{p:11,wr:54}, flex:["top"], dmg:"ad", a:{cc:2,engage:2,front:2,poke:0,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["Vayne","Olaf","Fiora","Teemo"], beats:["Ornn","Sion","KSante","Gnar"], syn:["Orianna","Vi"], blind:true },
  "Gnar":        { id:"Gnar", roles:{top:{wr:49.6,pr:2.8,tier:"B"}}, pro:{p:24,wr:54}, flex:["top"], dmg:"mix", a:{cc:3,engage:2,front:2,poke:2,split:1,early:2,late:2,peel:1,wave:1}, counteredBy:["Aatrox","Irelia","Zaahen","Sion","Jayce"], beats:["Darius","Sett","Olaf","Urgot","Wukong"], syn:["Orianna","Yasuo","Rell"], blind:false },
  "Renekton":    { id:"Renekton", roles:{top:{wr:49.4,pr:2.9,tier:"B"}}, pro:{p:21,wr:50}, flex:["top","mid"], dmg:"ad", a:{cc:2,engage:2,front:2,poke:0,split:1,early:3,late:1,peel:0,wave:2}, counteredBy:["Vayne","Olaf","KSante","Kayle"], beats:["Jayce","Irelia","Riven","Gwen","Camille"], syn:["XinZhao","LeeSin","Nocturne"], blind:true },
  "Ambessa":     { id:"Ambessa", roles:{top:{wr:48.9,pr:2.6,tier:"B"}}, pro:{p:40,wr:49}, flex:["top","jungle"], dmg:"ad", a:{cc:2,engage:2,front:2,poke:0,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["Malphite","Jax","Poppy","Olaf"], beats:["Gnar","Jayce","KSante","Gwen"], syn:["Orianna","Karma"], blind:true },
  "Rumble":      { id:"Rumble", roles:{top:{wr:49.5,pr:1.9,tier:"B"},mid:{wr:49.8,pr:1.0,tier:"B"}}, pro:{p:56,wr:54}, flex:["top","mid","jungle"], dmg:"ap", a:{cc:1,engage:1,front:1,poke:2,split:1,early:2,late:2,peel:1,wave:3}, counteredBy:["Irelia","Olaf","Yone","Vayne"], beats:["Sion","Ornn","KSante","Gnar","Jax"], syn:["JarvanIV","Amumu","Sion"], blind:false },
  "Yorick":      { id:"Yorick", roles:{top:{wr:50.7,pr:2.0,tier:"A"}}, pro:{p:8,wr:48}, flex:["top"], dmg:"ad", a:{cc:1,engage:0,front:1,poke:1,split:3,early:2,late:2,peel:0,wave:3}, counteredBy:["Sylas","Gwen","Darius","Olaf"], beats:["Sion","Ornn","Malphite","KSante","Singed"], syn:["TwistedFate","Shen"], blind:false },
  "Fiora":       { id:"Fiora", roles:{top:{wr:49.9,pr:3.2,tier:"B"}}, pro:{p:4,wr:51}, flex:["top"], dmg:"ad", a:{cc:1,engage:1,front:0,poke:0,split:3,early:2,late:3,peel:0,wave:1}, counteredBy:["Poppy","Malphite","Warwick","Pantheon"], beats:["Aatrox","Sion","Ornn","DrMundo","Malphite","KSante"], syn:["Shen","TwistedFate"], blind:false },
  "Mordekaiser": { id:"Mordekaiser", roles:{top:{wr:50.5,pr:3.4,tier:"A"}}, pro:{p:2,wr:48}, flex:["top"], dmg:"ap", a:{cc:1,engage:1,front:2,poke:0,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["Fiora","Gwen","Vayne","Olaf"], beats:["Shen","Sett","KSante","Garen"], syn:["Nocturne","Vi"], blind:true },
  "Poppy":       { id:"Poppy", roles:{support:{wr:50.5,pr:2.0,tier:"A"},top:{wr:49.8,pr:1.0,tier:"B"},jungle:{wr:49.6,pr:1.0,tier:"B"}}, pro:{p:6,wr:50}, flex:["jungle","support","top"], dmg:"mix", a:{cc:3,engage:1,front:2,poke:0,split:0,early:2,late:1,peel:3,wave:1}, counteredBy:["Darius","Mordekaiser","Teemo"], beats:["Camille","Jax","Riven","LeeSin","Vi"], syn:["Caitlyn","Jinx","Aphelios"], blind:true },
  "Wukong":      { id:"MonkeyKing", roles:{jungle:{wr:51.6,pr:4.8,tier:"S"},top:{wr:52.7,pr:1.2,tier:"S"}}, pro:{p:24,wr:44}, flex:["jungle","top"], dmg:"ad", a:{cc:3,engage:3,front:2,poke:0,split:1,early:2,late:2,peel:0,wave:1}, counteredBy:["Poppy","Rammus","Jax","Vi"], beats:["Gnar","Graves","Karthus","Belveth"], syn:["Yasuo","Orianna","Samira","MissFortune"], blind:true },

  // ============ JUNGLE ============
  "RekSai":      { id:"RekSai", name:"Rek'Sai", roles:{jungle:{wr:53.3,pr:3.1,tier:"S"}}, pro:{p:5,wr:52}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:0,split:1,early:3,late:1,peel:1,wave:1}, counteredBy:["Rammus","Poppy","Jax"], beats:["Graves","Nidalee","Kindred","Karthus"], syn:["Renekton","LeBlanc","Pantheon"], blind:true },
  "Sylas":       { id:"Sylas", roles:{mid:{wr:50.9,pr:9.0,tier:"S"},jungle:{wr:50.1,pr:8.1,tier:"A"}}, pro:{p:8,wr:45}, flex:["mid","jungle","top"], dmg:"ap", a:{cc:2,engage:2,front:1,poke:0,split:1,early:2,late:2,peel:0,wave:2}, counteredBy:["Malzahar","Viktor","Lissandra","Naafiri"], beats:["Teemo","Heimerdinger","Seraphine","Orianna","Azir"], syn:["Malphite","Orianna","Rell"], blind:false },
  "Graves":      { id:"Graves", roles:{jungle:{wr:49.6,pr:12.1,tier:"A"}}, pro:{p:5,wr:48}, flex:["jungle"], dmg:"ad", a:{cc:1,engage:0,front:1,poke:1,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["RekSai","Wukong","Poppy","Rammus"], beats:["Karthus","Lillia","Kindred","Ivern"], syn:["TwistedFate","Ryze"], blind:true },
  "Naafiri":     { id:"Naafiri", roles:{jungle:{wr:50.2,pr:6.7,tier:"A"},mid:{wr:50.2,pr:2.4,tier:"S"}}, pro:{p:13,wr:48}, flex:["jungle","mid"], dmg:"ad", a:{cc:1,engage:2,front:0,poke:1,split:2,early:2,late:1,peel:0,wave:2}, counteredBy:["Rammus","Poppy","Jax","Zed"], beats:["Sylas","Ahri","Lux","Karthus"], syn:["Nautilus","Rell"], blind:false },
  "Nocturne":    { id:"Nocturne", roles:{jungle:{wr:50.4,pr:6.8,tier:"A"}}, pro:{p:39,wr:53}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:3,front:1,poke:0,split:1,early:2,late:2,peel:0,wave:1}, counteredBy:["Rammus","Poppy","Lulu","Vi"], beats:["Karthus","Lillia","Kindred","Nidalee"], syn:["TwistedFate","Darius","Neeko"], blind:true },
  "Belveth":     { id:"Belveth", name:"Bel'Veth", roles:{jungle:{wr:52.2,pr:2.2,tier:"S"}}, pro:{p:3,wr:50}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:0,split:2,early:2,late:3,peel:0,wave:2}, counteredBy:["Wukong","Jax","Rammus","Vi"], beats:["Karthus","Nidalee","Lillia","Graves"], syn:["Orianna","Lulu"], blind:true },
  "Nasus":       { id:"Nasus", roles:{jungle:{wr:52.5,pr:1.6,tier:"S"},top:{wr:49.9,pr:2.5,tier:"B"}}, pro:{p:2,wr:49}, flex:["jungle"], dmg:"mix", a:{cc:2,engage:1,front:2,poke:0,split:3,early:1,late:3,peel:0,wave:2}, counteredBy:["Vayne","Kayle","Olaf","Darius"], beats:["Karthus","Lillia","Ivern"], syn:["TwistedFate","Zilean"], blind:true },
  "Rammus":      { id:"Rammus", roles:{jungle:{wr:52.5,pr:1.7,tier:"S"}}, pro:{p:2,wr:50}, flex:["jungle"], dmg:"mix", a:{cc:3,engage:3,front:3,poke:0,split:0,early:1,late:2,peel:1,wave:1}, counteredBy:["Karthus","Lillia","Kindred","Mordekaiser"], beats:["MasterYi","Belveth","Wukong","Briar","Naafiri"], syn:["Yasuo","Katarina"], blind:false },
  "JarvanIV":    { id:"JarvanIV", name:"Jarvan IV", roles:{jungle:{wr:50.3,pr:7.0,tier:"A"}}, pro:{p:54,wr:53}, flex:["jungle"], dmg:"ad", a:{cc:3,engage:3,front:2,poke:0,split:0,early:2,late:1,peel:1,wave:1}, counteredBy:["Rammus","Poppy","Olaf","Vi"], beats:["Karthus","Kindred","Lillia","Nidalee"], syn:["Rumble","Orianna","Galio","Yasuo"], blind:true },
  "Shyvana":     { id:"Shyvana", roles:{jungle:{wr:51.1,pr:3.9,tier:"S"}}, pro:{p:2,wr:49}, flex:["jungle"], dmg:"mix", a:{cc:1,engage:2,front:2,poke:0,split:2,early:1,late:3,peel:0,wave:2}, counteredBy:["Kindred","Nidalee","RekSai","Udyr"], beats:["Nasus","Rammus","Ivern"], syn:["Orianna","Lulu"], blind:true },
  "LeeSin":      { id:"LeeSin", name:"Lee Sin", roles:{jungle:{wr:48.8,pr:14.2,tier:"B"}}, pro:{p:11,wr:55}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:0,split:1,early:3,late:1,peel:1,wave:1}, counteredBy:["Rammus","Poppy","Udyr","Warwick"], beats:["Karthus","Lillia","Kindred","Ivern"], syn:["Yasuo","Renekton","Orianna"], blind:false },
  "Warwick":     { id:"Warwick", roles:{jungle:{wr:51.4,pr:3.0,tier:"S"},top:{wr:50.8,pr:1.2,tier:"A"}}, pro:{p:3,wr:50}, flex:["jungle"], dmg:"mix", a:{cc:2,engage:2,front:2,poke:0,split:1,early:3,late:1,peel:0,wave:1}, counteredBy:["Kindred","Lillia","Nidalee","Vayne"], beats:["LeeSin","Briar","Fiora","MasterYi"], syn:["Darius","Renekton"], blind:true },
  "Kayn":        { id:"Kayn", roles:{jungle:{wr:50.0,pr:7.0,tier:"A"}}, pro:{p:3,wr:48}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:0,split:2,early:1,late:2,peel:0,wave:2}, counteredBy:["RekSai","Udyr","Warwick","LeeSin"], beats:["Karthus","Lillia","Graves","Kindred"], syn:["Orianna","Galio"], blind:true },
  "Briar":       { id:"Briar", roles:{jungle:{wr:50.5,pr:4.7,tier:"A"}}, pro:{p:4,wr:49}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:3,front:1,poke:0,split:1,early:2,late:2,peel:0,wave:1}, counteredBy:["Rammus","Warwick","Poppy","Lulu"], beats:["Karthus","Nidalee","Graves","Kindred"], syn:["Neeko","Orianna"], blind:false },
  "Nidalee":     { id:"Nidalee", roles:{jungle:{wr:50.9,pr:3.6,tier:"A"}}, pro:{p:4,wr:50}, flex:["jungle"], dmg:"ap", a:{cc:0,engage:1,front:0,poke:3,split:1,early:3,late:1,peel:1,wave:1}, counteredBy:["Rammus","Udyr","Warwick","RekSai"], beats:["Karthus","Nasus","Shyvana","Ivern"], syn:["Jayce","Caitlyn"], blind:false },
  "Viego":       { id:"Viego", roles:{jungle:{wr:49.2,pr:9.7,tier:"B"}}, pro:{p:6,wr:49}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:0,split:2,early:2,late:2,peel:0,wave:1}, counteredBy:["Jax","Rammus","Poppy","Wukong"], beats:["Karthus","Lillia","Kindred","Nidalee"], syn:["Orianna","Yone"], blind:true },
  "Talon":       { id:"Talon", roles:{jungle:{wr:50.1,pr:5.1,tier:"A"},mid:{wr:50.1,pr:2.3,tier:"S"}}, pro:{p:2,wr:49}, flex:["jungle","mid"], dmg:"ad", a:{cc:1,engage:2,front:0,poke:1,split:2,early:3,late:1,peel:0,wave:3}, counteredBy:["Rammus","Poppy","Galio","Malzahar"], beats:["Karthus","Lux","Xerath","Seraphine"], syn:["Nocturne","TwistedFate"], blind:false },
  "Diana":       { id:"Diana", roles:{jungle:{wr:50.2,pr:4.9,tier:"A"},mid:{wr:50.6,pr:4.2,tier:"S"}}, pro:{p:3,wr:50}, flex:["jungle","mid"], dmg:"ap", a:{cc:2,engage:3,front:1,poke:0,split:1,early:1,late:3,peel:0,wave:2}, counteredBy:["Rammus","Poppy","Galio","Fizz"], beats:["Karthus","Lillia","Graves","Lux"], syn:["Yasuo","Yone","Malphite"], blind:true },
  "MasterYi":    { id:"MasterYi", name:"Master Yi", roles:{jungle:{wr:49.7,pr:6.2,tier:"B"}}, pro:{p:1,wr:45}, flex:["jungle"], dmg:"ad", a:{cc:0,engage:1,front:0,poke:0,split:2,early:1,late:3,peel:0,wave:1}, counteredBy:["Rammus","Jax","Warwick","Poppy"], beats:["Karthus","Lillia","Nidalee"], syn:["Kayle","Lulu","Taric"], blind:false },
  "Shaco":       { id:"Shaco", roles:{jungle:{wr:50.2,pr:4.3,tier:"A"}}, pro:{p:2,wr:48}, flex:["jungle","support"], dmg:"mix", a:{cc:1,engage:1,front:0,poke:0,split:2,early:3,late:1,peel:0,wave:1}, counteredBy:["Rammus","Warwick","RekSai","Udyr"], beats:["Karthus","Lillia","Kindred","Ivern"], syn:["Neeko","TwistedFate"], blind:false },
  "Ekko":        { id:"Ekko", roles:{jungle:{wr:50.4,pr:4.1,tier:"A"},mid:{wr:50.8,pr:3.1,tier:"S"}}, pro:{p:4,wr:50}, flex:["jungle","mid"], dmg:"ap", a:{cc:2,engage:2,front:1,poke:0,split:1,early:1,late:3,peel:1,wave:2}, counteredBy:["Rammus","Udyr","RekSai","Malzahar"], beats:["Karthus","Lillia","Graves","Lux"], syn:["Yasuo","Malphite"], blind:true },
  "Evelynn":     { id:"Evelynn", roles:{jungle:{wr:50.9,pr:2.6,tier:"A"}}, pro:{p:1,wr:47}, flex:["jungle"], dmg:"ap", a:{cc:1,engage:2,front:0,poke:0,split:1,early:1,late:3,peel:0,wave:1}, counteredBy:["Rammus","Warwick","Udyr","Vi"], beats:["Karthus","Lillia","Graves","Belveth"], syn:["Orianna","Galio"], blind:false },
  "Skarner":     { id:"Skarner", roles:{jungle:{wr:52.1,pr:1.1,tier:"S"},top:{wr:50.2,pr:0.6,tier:"B"}}, pro:{p:7,wr:51}, flex:["jungle","top"], dmg:"mix", a:{cc:3,engage:3,front:3,poke:0,split:0,early:1,late:2,peel:2,wave:1}, counteredBy:["Olaf","Kindred","Lillia","DrMundo"], beats:["Belveth","MasterYi","Graves","Kayn"], syn:["Orianna","Azir","Aphelios"], blind:true },
  "Udyr":        { id:"Udyr", roles:{jungle:{wr:51.2,pr:2.0,tier:"S"}}, pro:{p:4,wr:50}, flex:["jungle","top"], dmg:"mix", a:{cc:2,engage:2,front:2,poke:0,split:1,early:2,late:2,peel:1,wave:1}, counteredBy:["Kindred","Lillia","Vayne","Mordekaiser"], beats:["LeeSin","Kayn","Shaco","Nidalee"], syn:["Orianna","Karma"], blind:true },
  "Vi":          { id:"Vi", roles:{jungle:{wr:49.6,pr:5.4,tier:"B"}}, pro:{p:36,wr:53}, flex:["jungle"], dmg:"ad", a:{cc:3,engage:3,front:2,poke:0,split:0,early:2,late:1,peel:1,wave:1}, counteredBy:["Rammus","Jax","Poppy","Udyr"], beats:["Nocturne","Evelynn","Karthus","Belveth"], syn:["Orianna","Aurora","Caitlyn"], blind:true },
  "Ivern":       { id:"Ivern", roles:{jungle:{wr:51.6,pr:1.1,tier:"S"}}, pro:{p:3,wr:50}, flex:["jungle"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:0,split:0,early:1,late:2,peel:3,wave:1}, counteredBy:["Graves","Nidalee","Shaco","RekSai"], beats:["Karthus","Lillia"], syn:["MasterYi","Jinx","Kayle"], blind:false },
  "Lillia":      { id:"Lillia", roles:{jungle:{wr:50.3,pr:2.5,tier:"A"}}, pro:{p:4,wr:49}, flex:["jungle"], dmg:"ap", a:{cc:2,engage:1,front:1,poke:1,split:1,early:1,late:3,peel:1,wave:2}, counteredBy:["RekSai","Udyr","Warwick","Vi"], beats:["Rammus","Skarner","Nasus","Sion"], syn:["Orianna","Ashe"], blind:false },
  "Kindred":     { id:"Kindred", roles:{jungle:{wr:50.3,pr:2.5,tier:"A"}}, pro:{p:3,wr:49}, flex:["jungle"], dmg:"ad", a:{cc:1,engage:1,front:0,poke:1,split:1,early:2,late:3,peel:2,wave:1}, counteredBy:["RekSai","Vi","JarvanIV","Udyr"], beats:["Rammus","Shyvana","Nasus","Udyr"], syn:["Kayle","Lulu","Orianna"], blind:false },
  "XinZhao":     { id:"XinZhao", name:"Xin Zhao", roles:{jungle:{wr:49.8,pr:3.5,tier:"B"},mid:{wr:49.0,pr:0.8,tier:"B"}}, pro:{p:36,wr:49}, flex:["jungle","mid"], dmg:"mix", a:{cc:2,engage:2,front:1,poke:0,split:0,early:3,late:1,peel:1,wave:1}, counteredBy:["Jax","Rammus","Poppy","Warwick"], beats:["Graves","Karthus","Kindred","Nidalee"], syn:["Renekton","Orianna","Ahri"], blind:true },
  "Karthus":     { id:"Karthus", roles:{jungle:{wr:50.8,pr:1.4,tier:"A"},adc:{wr:54.1,pr:0.7,tier:"S"}}, pro:{p:2,wr:48}, flex:["jungle"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:1,split:1,early:1,late:3,peel:0,wave:3}, counteredBy:["LeeSin","Nocturne","RekSai","Graves","XinZhao"], beats:["Rammus","Nasus","Skarner","Udyr"], syn:["Ashe","Amumu"], blind:false },
  "Amumu":       { id:"Amumu", roles:{jungle:{wr:50.6,pr:1.8,tier:"A"},support:{wr:50.4,pr:1.0,tier:"A"}}, pro:{p:2,wr:49}, flex:["jungle","support"], dmg:"ap", a:{cc:3,engage:3,front:2,poke:0,split:0,early:1,late:2,peel:1,wave:1}, counteredBy:["Kindred","Lillia","Graves","Nidalee"], beats:["Rammus","MasterYi","Nasus"], syn:["Katarina","MissFortune","Yasuo","Karthus"], blind:false },
  "Zac":         { id:"Zac", roles:{jungle:{wr:50.7,pr:2.4,tier:"A"}}, pro:{p:5,wr:50}, flex:["jungle","top"], dmg:"ap", a:{cc:3,engage:3,front:3,poke:0,split:0,early:1,late:2,peel:1,wave:1}, counteredBy:["Kindred","Lillia","Vayne","Gwen"], beats:["Rammus","Nasus","MasterYi"], syn:["Yasuo","Orianna","MissFortune"], blind:true },

  // ============ MID ============
  "Syndra":      { id:"Syndra", roles:{mid:{wr:51.8,pr:7.2,tier:"S"}}, pro:{p:6,wr:51}, flex:["mid"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:2,split:0,early:2,late:3,peel:2,wave:2}, counteredBy:["Fizz","Irelia","Yasuo","Sylas"], beats:["Azir","Orianna","Viktor","TwistedFate"], syn:["JarvanIV","Vi","Nautilus"], blind:true },
  "Fizz":        { id:"Fizz", roles:{mid:{wr:52.1,pr:5.5,tier:"S"}}, pro:{p:1,wr:48}, flex:["mid"], dmg:"ap", a:{cc:1,engage:2,front:0,poke:0,split:1,early:2,late:2,peel:0,wave:1}, counteredBy:["Lissandra","Galio","Vex","Annie"], beats:["Syndra","Xerath","Lux","Viktor","Hwei"], syn:["Nautilus","Vi"], blind:false },
  "Ahri":        { id:"Ahri", roles:{mid:{wr:50.7,pr:9.9,tier:"S"}}, pro:{p:21,wr:54}, flex:["mid"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:1,split:0,early:2,late:2,peel:1,wave:2}, counteredBy:["Yasuo","Fizz","Naafiri","Irelia"], beats:["Orianna","Azir","Viktor","Ryze"], syn:["JarvanIV","Vi","Rell"], blind:true },
  "Katarina":    { id:"Katarina", roles:{mid:{wr:51.1,pr:7.0,tier:"S"}}, pro:{p:1,wr:46}, flex:["mid"], dmg:"mix", a:{cc:0,engage:2,front:0,poke:0,split:0,early:2,late:3,peel:0,wave:2}, counteredBy:["Galio","Lissandra","Malzahar","Diana"], beats:["Lux","Xerath","Syndra","Hwei"], syn:["Amumu","Malphite","Rell"], blind:false },
  "Viktor":      { id:"Viktor", roles:{mid:{wr:49.9,pr:10.3,tier:"A"}}, pro:{p:13,wr:49}, flex:["mid"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:2,split:0,early:1,late:3,peel:1,wave:3}, counteredBy:["Fizz","Sylas","Yasuo","Naafiri"], beats:["Azir","Ryze","Orianna","Anivia"], syn:["JarvanIV","Skarner","Rell"], blind:true },
  "Xerath":      { id:"Xerath", roles:{mid:{wr:51.3,pr:5.2,tier:"S"},support:{wr:50.2,pr:1.5,tier:"A"}}, pro:{p:2,wr:48}, flex:["mid","support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:1,wave:3}, counteredBy:["Fizz","Talon","Naafiri","Yasuo"], beats:["Viktor","Azir","Ryze","Anivia"], syn:["JarvanIV","Varus","Jhin"], blind:false },
  "Vladimir":    { id:"Vladimir", roles:{mid:{wr:51.4,pr:4.6,tier:"S"},top:{wr:50.0,pr:1.5,tier:"B"}}, pro:{p:2,wr:48}, flex:["mid","top"], dmg:"ap", a:{cc:0,engage:1,front:1,poke:1,split:1,early:0,late:3,peel:0,wave:2}, counteredBy:["Irelia","Sylas","Camille","Riven"], beats:["Orianna","Azir","Viktor","Lux"], syn:["JarvanIV","Wukong","Zilean"], blind:true },
  "Hwei":        { id:"Hwei", roles:{mid:{wr:50.7,pr:6.3,tier:"S"},adc:{wr:53.0,pr:1.3,tier:"A"}}, pro:{p:9,wr:50}, flex:["mid","adc","support"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:3,split:0,early:1,late:3,peel:2,wave:3}, counteredBy:["Fizz","Yasuo","Naafiri","Talon"], beats:["Viktor","Azir","Orianna","Anivia"], syn:["JarvanIV","Skarner","Vi"], blind:false },
  "TwistedFate": { id:"TwistedFate", name:"Twisted Fate", roles:{mid:{wr:50.8,pr:5.5,tier:"S"}}, pro:{p:5,wr:50}, flex:["mid","adc"], dmg:"mix", a:{cc:2,engage:0,front:0,poke:1,split:2,early:2,late:2,peel:1,wave:2}, counteredBy:["Fizz","Zed","Yasuo","Naafiri"], beats:["Anivia","Karthus","Vex"], syn:["Nocturne","Pantheon","TahmKench","Yorick"], blind:false },
  "Zed":         { id:"Zed", roles:{mid:{wr:49.3,pr:7.5,tier:"A"}}, pro:{p:2,wr:47}, flex:["mid"], dmg:"ad", a:{cc:0,engage:2,front:0,poke:1,split:2,early:2,late:2,peel:0,wave:2}, counteredBy:["Lissandra","Malzahar","Naafiri","Galio"], beats:["Syndra","Xerath","Lux","TwistedFate","Zoe"], syn:["Nocturne","JarvanIV"], blind:false },
  "Lissandra":   { id:"Lissandra", roles:{mid:{wr:50.8,pr:4.8,tier:"S"}}, pro:{p:5,wr:51}, flex:["mid"], dmg:"ap", a:{cc:3,engage:2,front:1,poke:1,split:0,early:2,late:2,peel:2,wave:2}, counteredBy:["Malzahar","Viktor","Syndra","Kassadin"], beats:["Zed","Fizz","Katarina","Akali","Yasuo","Sylas"], syn:["JarvanIV","Nocturne","MissFortune"], blind:true },
  "Veigar":      { id:"Veigar", roles:{mid:{wr:51.3,pr:3.1,tier:"S"},adc:{wr:52.5,pr:0.9,tier:"A"}}, pro:{p:1,wr:47}, flex:["mid"], dmg:"ap", a:{cc:3,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:2,wave:2}, counteredBy:["Sylas","Fizz","Zed","Irelia"], beats:["Viktor","Ryze","Vladimir","Kassadin"], syn:["Amumu","JarvanIV"], blind:false },
  "Vex":         { id:"Vex", roles:{mid:{wr:51.6,pr:2.4,tier:"S"}}, pro:{p:3,wr:50}, flex:["mid"], dmg:"ap", a:{cc:2,engage:2,front:0,poke:1,split:0,early:2,late:2,peel:2,wave:2}, counteredBy:["Malzahar","Syndra","Anivia","Viktor"], beats:["Fizz","Yasuo","Zed","Katarina","Sylas","Akali"], syn:["JarvanIV","Wukong","Rell"], blind:true },
  "Malzahar":    { id:"Malzahar", roles:{mid:{wr:49.5,pr:5.6,tier:"A"}}, pro:{p:1,wr:48}, flex:["mid"], dmg:"ap", a:{cc:3,engage:0,front:0,poke:1,split:1,early:1,late:2,peel:2,wave:3}, counteredBy:["Sylas","Yasuo","Katarina","Irelia"], beats:["Zed","Fizz","Akali","Katarina","Kassadin"], syn:["JarvanIV","Nocturne"], blind:true },
  "Akali":       { id:"Akali", roles:{mid:{wr:48.8,pr:6.0,tier:"B"},top:{wr:50.2,pr:2.8,tier:"B"}}, pro:{p:31,wr:54}, flex:["mid","top"], dmg:"ap", a:{cc:1,engage:2,front:0,poke:0,split:1,early:2,late:3,peel:0,wave:1}, counteredBy:["Malzahar","Lissandra","Galio","Vex"], beats:["Syndra","Lux","Xerath","Seraphine","Hwei"], syn:["Nocturne","JarvanIV","Skarner"], blind:false },
  "Lux":         { id:"Lux", roles:{mid:{wr:50.0,pr:3.6,tier:"S"},support:{wr:49.6,pr:6.3,tier:"A"},adc:{wr:55.3,pr:0.8,tier:"A"}}, pro:{p:2,wr:48}, flex:["mid","support"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:2,wave:2}, counteredBy:["Fizz","Yasuo","Talon","Katarina"], beats:["Viktor","Orianna","TwistedFate"], syn:["Caitlyn","Jhin","Garen"], blind:false },
  "Swain":       { id:"Swain", roles:{mid:{wr:53.4,pr:0.7,tier:"S"},support:{wr:50.1,pr:1.5,tier:"A"}}, pro:{p:2,wr:49}, flex:["mid","support","adc"], dmg:"ap", a:{cc:2,engage:2,front:2,poke:1,split:0,early:2,late:2,peel:1,wave:2}, counteredBy:["Fizz","Zed","Sylas","Akali"], beats:["Orianna","Ryze","Vladimir","Galio"], syn:["JarvanIV","Nautilus"], blind:true },
  "Galio":       { id:"Galio", roles:{mid:{wr:49.3,pr:4.4,tier:"A"},support:{wr:51.1,pr:0.9,tier:"A"}}, pro:{p:11,wr:44}, flex:["mid","support"], dmg:"ap", a:{cc:3,engage:3,front:2,poke:0,split:0,early:2,late:1,peel:2,wave:2}, counteredBy:["Syndra","Viktor","Xerath","Vladimir"], beats:["Katarina","Fizz","Akali","Yasuo","Yone"], syn:["JarvanIV","Camille","Nocturne","TwistedFate"], blind:true },
  "Yasuo":       { id:"Yasuo", roles:{mid:{wr:48.0,pr:6.8,tier:"B"},adc:{wr:51.3,pr:1.1,tier:"A"}}, pro:{p:5,wr:48}, flex:["mid","adc","top"], dmg:"ad", a:{cc:2,engage:2,front:0,poke:0,split:1,early:2,late:3,peel:1,wave:2}, counteredBy:["Annie","Malzahar","Lissandra","Galio"], beats:["Syndra","Lux","Xerath","Zoe","Hwei"], syn:["Malphite","Alistar","JarvanIV","Wukong","Rell","Gnar"], blind:false },
  "LeBlanc":     { id:"Leblanc", name:"LeBlanc", roles:{mid:{wr:49.4,pr:3.9,tier:"A"}}, pro:{p:6,wr:50}, flex:["mid"], dmg:"ap", a:{cc:1,engage:1,front:0,poke:2,split:1,early:3,late:1,peel:0,wave:1}, counteredBy:["Malzahar","Galio","Lissandra","Kassadin"], beats:["Orianna","Azir","Syndra","Viktor"], syn:["RekSai","LeeSin","Nocturne"], blind:false },
  "Annie":       { id:"Annie", roles:{mid:{wr:50.5,pr:2.3,tier:"S"},support:{wr:49.8,pr:0.6,tier:"B"}}, pro:{p:1,wr:48}, flex:["mid","support"], dmg:"ap", a:{cc:3,engage:2,front:0,poke:1,split:0,early:2,late:2,peel:2,wave:2}, counteredBy:["Viktor","Syndra","Xerath","Vladimir"], beats:["Yasuo","Zed","Fizz","Katarina"], syn:["JarvanIV","Amumu"], blind:true },
  "Zoe":         { id:"Zoe", roles:{mid:{wr:49.9,pr:2.9,tier:"A"}}, pro:{p:2,wr:49}, flex:["mid"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:1,wave:1}, counteredBy:["Fizz","Yasuo","Zed","Irelia"], beats:["Lux","Xerath","Orianna","Syndra"], syn:["JarvanIV","Nocturne"], blind:false },
  "Kassadin":    { id:"Kassadin", roles:{mid:{wr:49.9,pr:2.8,tier:"A"}}, pro:{p:1,wr:48}, flex:["mid"], dmg:"ap", a:{cc:1,engage:2,front:0,poke:0,split:1,early:0,late:3,peel:0,wave:2}, counteredBy:["Malzahar","Veigar","Lissandra","Irelia"], beats:["Syndra","Viktor","Xerath","Ahri","Vladimir"], syn:["JarvanIV","Skarner"], blind:false },
  "Orianna":     { id:"Orianna", roles:{mid:{wr:49.8,pr:4.0,tier:"A"}}, pro:{p:77,wr:53}, flex:["mid"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:2,split:0,early:2,late:3,peel:3,wave:3}, counteredBy:["Fizz","Sylas","Ahri","LeBlanc","Yasuo"], beats:["Azir","Ryze","Taliyah","TwistedFate"], syn:["JarvanIV","Wukong","Vi","Skarner","Aatrox","Zac"], blind:true },
  "Azir":        { id:"Azir", roles:{mid:{wr:48.7,pr:2.2,tier:"B"}}, pro:{p:31,wr:46}, flex:["mid"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:2,split:1,early:1,late:3,peel:2,wave:3}, counteredBy:["Syndra","Ahri","Sylas","Irelia","Naafiri"], beats:["Ryze","Anivia","Karthus","Vladimir"], syn:["Ornn","KSante","Skarner","Renekton"], blind:false },
  "Ryze":        { id:"Ryze", roles:{mid:{wr:48.5,pr:2.5,tier:"B"},top:{wr:48.2,pr:1.0,tier:"B"}}, pro:{p:47,wr:51}, flex:["mid","top"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:1,split:2,early:1,late:3,peel:1,wave:3}, counteredBy:["Yone","Irelia","Camille","Tryndamere","Azir"], beats:["Anivia","Karthus","Galio","Swain"], syn:["Graves","Shen","Skarner"], blind:false },
  "Anivia":      { id:"Anivia", roles:{mid:{wr:51.0,pr:1.8,tier:"A"}}, pro:{p:17,wr:55}, flex:["mid"], dmg:"ap", a:{cc:3,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:2,wave:3}, counteredBy:["TwistedFate","Ryze","Azir","Xerath","Hwei"], beats:["Yone","Yasuo","Katarina","Irelia","Sylas"], syn:["JarvanIV","Vi","Nautilus"], blind:true },
  "Taliyah":     { id:"Taliyah", roles:{mid:{wr:49.7,pr:1.5,tier:"B"},jungle:{wr:50.0,pr:1.3,tier:"A"}}, pro:{p:17,wr:48}, flex:["mid","jungle"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:2,split:0,early:2,late:2,peel:2,wave:3}, counteredBy:["Yasuo","Fizz","Irelia","Orianna"], beats:["Azir","Ryze","Anivia","Karthus"], syn:["Renekton","Pantheon","Nocturne"], blind:false },
  "Cassiopeia":  { id:"Cassiopeia", roles:{top:{wr:53.4,pr:0.7,tier:"S"},mid:{wr:51.0,pr:1.8,tier:"A"}}, pro:{p:15,wr:55}, flex:["mid","top"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:1,split:1,early:2,late:3,peel:2,wave:3}, counteredBy:["Sylas","Yasuo","Irelia","Sion"], beats:["Singed","Yone","Riven","Vladimir","Ryze"], syn:["JarvanIV","Skarner","Nautilus"], blind:true },
  "Aurora":      { id:"Aurora", roles:{mid:{wr:49.0,pr:2.0,tier:"B"},top:{wr:48.6,pr:1.4,tier:"B"}}, pro:{p:26,wr:45}, flex:["mid","top"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:2,split:0,early:2,late:2,peel:1,wave:2}, counteredBy:["Irelia","Fizz","Yasuo","Ornn"], beats:["Azir","Ryze","Viktor","KSante"], syn:["Vi","JarvanIV","Nautilus"], blind:false },
  "Mel":         { id:"Mel", roles:{mid:{wr:48.5,pr:1.8,tier:"B"},support:{wr:48.9,pr:1.2,tier:"B"}}, pro:{p:9,wr:39}, flex:["mid","support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:2,wave:2}, counteredBy:["Fizz","Yasuo","Naafiri","Talon"], beats:["Xerath","Lux","Viktor","Hwei"], syn:["JarvanIV","Vi"], blind:false },
  "Qiyana":      { id:"Qiyana", roles:{mid:{wr:49.6,pr:1.6,tier:"B"},jungle:{wr:49.4,pr:1.2,tier:"B"}}, pro:{p:7,wr:50}, flex:["mid","jungle"], dmg:"ad", a:{cc:2,engage:2,front:0,poke:0,split:1,early:2,late:2,peel:0,wave:2}, counteredBy:["Malzahar","Lissandra","Galio","Poppy"], beats:["Lux","Xerath","Syndra","Seraphine"], syn:["Yasuo","JarvanIV","Rell"], blind:false },
  "Neeko":       { id:"Neeko", roles:{mid:{wr:50.1,pr:2.2,tier:"A"},support:{wr:49.9,pr:1.6,tier:"B"}}, pro:{p:35,wr:51}, flex:["mid","support"], dmg:"ap", a:{cc:3,engage:2,front:0,poke:1,split:0,early:2,late:2,peel:1,wave:2}, counteredBy:["Fizz","Yasuo","Sylas","Akali"], beats:["Viktor","Lux","Orianna","Azir"], syn:["Nocturne","Briar","JarvanIV","Wukong"], blind:true },
  "Corki":       { id:"Corki", roles:{mid:{wr:49.3,pr:1.3,tier:"B"},adc:{wr:48.9,pr:1.5,tier:"B"}}, pro:{p:21,wr:48}, flex:["adc","mid"], dmg:"mix", a:{cc:0,engage:0,front:0,poke:2,split:1,early:1,late:3,peel:0,wave:2}, counteredBy:["Yasuo","Zed","Irelia","Fizz"], beats:["Azir","Ryze","Anivia"], syn:["Orianna","Braum","Lulu"], blind:true },

  // ============ ADC ============
  "Senna":       { id:"Senna", roles:{adc:{wr:54.7,pr:16.5,tier:"S"},support:{wr:51.8,pr:6.9,tier:"S"}}, pro:{p:10,wr:51}, flex:["adc","support"], dmg:"ad", a:{cc:2,engage:0,front:0,poke:2,split:0,early:2,late:3,peel:2,wave:1}, counteredBy:["Pyke","Blitzcrank","Nautilus","Samira"], beats:["Jhin","Caitlyn","Ezreal","Ashe"], syn:["TahmKench","Sion","Seraphine"], blind:true },
  "Jinx":        { id:"Jinx", roles:{adc:{wr:51.6,pr:11.2,tier:"S"}}, pro:{p:6,wr:51}, flex:["adc"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:0,wave:2}, counteredBy:["Samira","Lucian","Tristana","Draven"], beats:["Vayne","Zeri","Aphelios","Nilah"], syn:["Lulu","Thresh","Braum","Ivern"], blind:true },
  "Ashe":        { id:"Ashe", roles:{adc:{wr:50.3,pr:11.6,tier:"S"},support:{wr:49.7,pr:2.5,tier:"B"}}, pro:{p:26,wr:58}, flex:["adc","support"], dmg:"ad", a:{cc:3,engage:2,front:0,poke:2,split:0,early:2,late:2,peel:1,wave:1}, counteredBy:["Samira","Tristana","Draven","Lucian"], beats:["Jhin","Caitlyn","Zeri","Aphelios"], syn:["Karma","Braum","Lillia","Vi"], blind:true },
  "Caitlyn":     { id:"Caitlyn", roles:{adc:{wr:49.1,pr:15.2,tier:"A"}}, pro:{p:24,wr:55}, flex:["adc"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:3,split:0,early:3,late:2,peel:1,wave:2}, counteredBy:["Samira","Nilah","Tristana","Yasuo"], beats:["Zeri","Vayne","Nilah","Twitch"], syn:["Lux","Karma","Morgana","Vi"], blind:false },
  "Jhin":        { id:"Jhin", roles:{adc:{wr:49.1,pr:15.2,tier:"A"}}, pro:{p:13,wr:44}, flex:["adc"], dmg:"ad", a:{cc:2,engage:0,front:0,poke:2,split:0,early:2,late:2,peel:1,wave:1}, counteredBy:["Samira","Tristana","Lucian","Nilah"], beats:["Vayne","Twitch","Zeri","Kog'Maw"], syn:["Morgana","Zyra","Xerath","Nautilus"], blind:true },
  "Tristana":    { id:"Tristana", roles:{adc:{wr:50.6,pr:6.7,tier:"A"},mid:{wr:50.1,pr:1.0,tier:"A"}}, pro:{p:8,wr:50}, flex:["adc","mid"], dmg:"ad", a:{cc:1,engage:2,front:0,poke:0,split:2,early:2,late:2,peel:1,wave:2}, counteredBy:["Caitlyn","Ashe","Senna","Ziggs"], beats:["Jinx","Ashe","Caitlyn","Zeri","Smolder"], syn:["Leona","Nautilus","Rell"], blind:false },
  "Ezreal":      { id:"Ezreal", roles:{adc:{wr:47.8,pr:17.4,tier:"B"}}, pro:{p:36,wr:49}, flex:["adc"], dmg:"mix", a:{cc:0,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:0,wave:2}, counteredBy:["Senna","Caitlyn","Jhin","Ashe"], beats:["Zeri","Aphelios","Vayne"], syn:["Karma","Bard","Braum","Vi"], blind:true },
  "Brand":       { id:"Brand", roles:{adc:{wr:51.9,pr:2.9,tier:"A"},support:{wr:50.2,pr:3.4,tier:"A"},jungle:{wr:50.1,pr:1.5,tier:"B"}}, pro:{p:2,wr:47}, flex:["support","adc"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:2,split:0,early:2,late:2,peel:0,wave:2}, counteredBy:["Lucian","Tristana","Samira","Sylas"], beats:["Ezreal","Jhin","Caitlyn"], syn:["Amumu","JarvanIV"], blind:false },
  "Smolder":     { id:"Smolder", roles:{adc:{wr:49.9,pr:6.4,tier:"A"}}, pro:{p:6,wr:48}, flex:["adc"], dmg:"mix", a:{cc:1,engage:0,front:0,poke:2,split:1,early:0,late:3,peel:1,wave:3}, counteredBy:["Tristana","Lucian","Samira","Draven"], beats:["Jhin","Ashe","Caitlyn"], syn:["Lulu","Milio","Karma","Skarner"], blind:false },
  "Vayne":       { id:"Vayne", roles:{adc:{wr:50.1,pr:4.9,tier:"A"},top:{wr:50.9,pr:1.7,tier:"A"}}, pro:{p:10,wr:64}, flex:["adc","top"], dmg:"mix", a:{cc:1,engage:0,front:0,poke:0,split:2,early:1,late:3,peel:0,wave:1}, counteredBy:["Caitlyn","Draven","Samira","Miss Fortune"], beats:["Jinx","Aphelios","Kog'Maw","Smolder"], syn:["Lulu","Janna","Milio","Thresh"], blind:false },
  "Twitch":      { id:"Twitch", roles:{adc:{wr:50.3,pr:4.7,tier:"A"}}, pro:{p:2,wr:48}, flex:["adc"], dmg:"mix", a:{cc:1,engage:0,front:0,poke:0,split:1,early:1,late:3,peel:0,wave:1}, counteredBy:["Caitlyn","Jhin","Draven","Miss Fortune"], beats:["Vayne","Zeri","Nilah"], syn:["Lulu","Yuumi","Shen","Ivern"], blind:false },
  "Xayah":       { id:"Xayah", roles:{adc:{wr:51.0,pr:3.5,tier:"A"}}, pro:{p:6,wr:50}, flex:["adc"], dmg:"ad", a:{cc:2,engage:0,front:0,poke:1,split:0,early:2,late:3,peel:2,wave:2}, counteredBy:["Caitlyn","Draven","Samira","Lucian"], beats:["Tristana","Samira","Nilah","Zeri"], syn:["Rakan","Nautilus","Rell"], blind:true },
  "Ziggs":       { id:"Ziggs", roles:{adc:{wr:52.5,pr:1.8,tier:"A"}}, pro:{p:3,wr:49}, flex:["adc","mid"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:1,wave:3}, counteredBy:["Lucian","Samira","Tristana","Yasuo"], beats:["Jhin","Caitlyn","Ashe","Senna"], syn:["Leona","Nautilus","JarvanIV"], blind:false },
  "Kaisa":       { id:"Kaisa", name:"Kai'Sa", roles:{adc:{wr:47.9,pr:12.5,tier:"B"}}, pro:{p:6,wr:48}, flex:["adc"], dmg:"mix", a:{cc:0,engage:1,front:0,poke:1,split:0,early:1,late:3,peel:0,wave:1}, counteredBy:["Caitlyn","Ashe","Senna","Draven"], beats:["Vayne","Zeri","Twitch"], syn:["Nautilus","Leona","Rell","Alistar"], blind:true },
  "Samira":      { id:"Samira", roles:{adc:{wr:50.2,pr:4.5,tier:"A"}}, pro:{p:3,wr:48}, flex:["adc"], dmg:"ad", a:{cc:1,engage:2,front:0,poke:0,split:0,early:2,late:2,peel:0,wave:1}, counteredBy:["Xayah","Caitlyn","Senna","Janna"], beats:["Jinx","Ashe","Jhin","Senna","Caitlyn"], syn:["Rell","Nautilus","Leona","Alistar","Wukong"], blind:false },
  "Lucian":      { id:"Lucian", roles:{adc:{wr:48.7,pr:8.5,tier:"A"}}, pro:{p:18,wr:51}, flex:["adc"], dmg:"ad", a:{cc:0,engage:1,front:0,poke:1,split:0,early:3,late:1,peel:0,wave:2}, counteredBy:["Jinx","Ziggs","Xayah","Senna"], beats:["Jhin","Ashe","Zeri","Smolder","Brand"], syn:["Nami","Braum","Milio"], blind:false },
  "Karthus_adc": null, // (Karthus covered in jungle entry)
  "Zeri":        { id:"Zeri", roles:{adc:{wr:49.8,pr:4.5,tier:"A"}}, pro:{p:4,wr:48}, flex:["adc"], dmg:"mix", a:{cc:1,engage:0,front:0,poke:1,split:1,early:1,late:3,peel:0,wave:2}, counteredBy:["Caitlyn","Ashe","Tristana","Lucian"], beats:["Jhin","Senna","Smolder"], syn:["Lulu","Yuumi","Milio","Skarner"], blind:false },
  "MissFortune": { id:"MissFortune", name:"Miss Fortune", roles:{adc:{wr:49.0,pr:6.1,tier:"A"}}, pro:{p:3,wr:48}, flex:["adc"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:2,split:0,early:2,late:2,peel:0,wave:2}, counteredBy:["Samira","Tristana","Lucian","Vayne"], beats:["Twitch","Vayne","Jhin"], syn:["Amumu","Leona","Nautilus","Malphite","Wukong"], blind:true },
  "Sivir":       { id:"Sivir", roles:{adc:{wr:49.5,pr:4.3,tier:"A"}}, pro:{p:15,wr:51}, flex:["adc"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:2,wave:3}, counteredBy:["Caitlyn","Draven","Lucian","Samira"], beats:["Zeri","Aphelios","Vayne"], syn:["Lulu","Karma","Yuumi","Skarner"], blind:true },
  "Nilah":       { id:"Nilah", roles:{adc:{wr:52.0,pr:1.3,tier:"A"}}, pro:{p:3,wr:50}, flex:["adc"], dmg:"ad", a:{cc:2,engage:2,front:0,poke:0,split:0,early:2,late:3,peel:2,wave:1}, counteredBy:["Caitlyn","Ashe","Ziggs","Jhin"], beats:["Vayne","Zeri","Twitch","Samira"], syn:["Nami","Soraka","Milio","Rell"], blind:false },
  "Velkoz":      { id:"Velkoz", name:"Vel'Koz", roles:{support:{wr:50.4,pr:3.8,tier:"A"},adc:{wr:52.8,pr:0.8,tier:"A"}}, pro:{p:1,wr:47}, flex:["support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:3,split:0,early:2,late:2,peel:1,wave:2}, counteredBy:["Pyke","Blitzcrank","Rakan","Leona"], beats:["Soraka","Janna","Lulu","Braum"], syn:["Caitlyn","Jhin","Ashe"], blind:false },
  "Varus":       { id:"Varus", roles:{adc:{wr:48.9,pr:3.5,tier:"B"}}, pro:{p:62,wr:50}, flex:["adc"], dmg:"mix", a:{cc:2,engage:1,front:0,poke:2,split:0,early:2,late:2,peel:1,wave:2}, counteredBy:["Samira","Tristana","Lucian","Vayne"], beats:["Jhin","Ashe","Caitlyn","Aphelios"], syn:["Karma","Braum","JarvanIV","Jayce"], blind:true },
  "Yunara":      { id:"Yunara", roles:{adc:{wr:49.5,pr:5.5,tier:"A"}}, pro:{p:31,wr:49}, flex:["adc"], dmg:"mix", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:0,wave:2}, counteredBy:["Lucian","Tristana","Samira","Draven"], beats:["Jhin","Smolder","Zeri","Vayne"], syn:["Lulu","Milio","Karma","Braum"], blind:true },
  "Aphelios":    { id:"Aphelios", roles:{adc:{wr:48.8,pr:3.2,tier:"B"}}, pro:{p:9,wr:49}, flex:["adc"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:0,wave:2}, counteredBy:["Lucian","Samira","Tristana","Draven"], beats:["Smolder","Zeri","Senna"], syn:["Thresh","Lulu","Ornn","Braum","Skarner"], blind:false },
  "Kogmaw":      { id:"KogMaw", name:"Kog'Maw", roles:{adc:{wr:50.8,pr:2.2,tier:"A"}}, pro:{p:2,wr:49}, flex:["adc"], dmg:"mix", a:{cc:0,engage:0,front:0,poke:1,split:0,early:0,late:3,peel:0,wave:2}, counteredBy:["Tristana","Samira","Lucian","Vayne"], beats:["Jinx","Aphelios","Smolder"], syn:["Lulu","Milio","Braum","Ivern"], blind:false },
  "Draven":      { id:"Draven", roles:{adc:{wr:49.8,pr:3.3,tier:"B"}}, pro:{p:2,wr:48}, flex:["adc"], dmg:"ad", a:{cc:1,engage:0,front:0,poke:0,split:0,early:3,late:2,peel:0,wave:1}, counteredBy:["Senna","Ziggs","Caitlyn","Janna"], beats:["Vayne","Twitch","Zeri","Jinx","Kogmaw"], syn:["Leona","Nautilus","Thresh","Blitzcrank"], blind:false },

  // ============ SUPPORT ============
  "Thresh":      { id:"Thresh", roles:{support:{wr:51.4,pr:13.4,tier:"S"}}, pro:{p:5,wr:50}, flex:["support"], dmg:"mix", a:{cc:3,engage:2,front:1,poke:0,split:0,early:2,late:2,peel:3,wave:0}, counteredBy:["Morgana","Lulu","Janna","Seraphine"], beats:["Soraka","Sona","Nami","Yuumi"], syn:["Aphelios","Jinx","Draven","Samira"], blind:true },
  "Leona":       { id:"Leona", roles:{support:{wr:52.1,pr:8.0,tier:"S"}}, pro:{p:10,wr:47}, flex:["support"], dmg:"mix", a:{cc:3,engage:3,front:2,poke:0,split:0,early:3,late:1,peel:2,wave:0}, counteredBy:["Morgana","Janna","Lulu","Milio"], beats:["Soraka","Nami","Sona","Yuumi","Karma"], syn:["Samira","Kaisa","Tristana","Draven","MissFortune"], blind:true },
  "Seraphine":   { id:"Seraphine", roles:{support:{wr:51.0,pr:10.6,tier:"S"},adc:{wr:53.1,pr:1.6,tier:"A"}}, pro:{p:23,wr:54}, flex:["support","adc","mid"], dmg:"ap", a:{cc:3,engage:1,front:0,poke:2,split:0,early:1,late:3,peel:3,wave:2}, counteredBy:["Blitzcrank","Pyke","Nautilus","Leona"], beats:["Karma","Nami","Sona","Braum"], syn:["Senna","JarvanIV","Wukong","Amumu"], blind:true },
  "Bard":        { id:"Bard", roles:{support:{wr:50.9,pr:7.8,tier:"S"}}, pro:{p:38,wr:57}, flex:["support"], dmg:"mix", a:{cc:3,engage:2,front:1,poke:1,split:0,early:2,late:2,peel:2,wave:0}, counteredBy:["Morgana","Lulu","Blitzcrank","Janna"], beats:["Soraka","Sona","Yuumi","Nami"], syn:["Ezreal","Jhin","Varus","Nocturne"], blind:true },
  "Braum":       { id:"Braum", roles:{support:{wr:51.7,pr:4.7,tier:"S"}}, pro:{p:9,wr:45}, flex:["support"], dmg:"mix", a:{cc:3,engage:1,front:2,poke:0,split:0,early:2,late:2,peel:3,wave:0}, counteredBy:["Zyra","Brand","Lux","Vel'Koz"], beats:["Blitzcrank","Pyke","Leona","Nautilus"], syn:["Lucian","Ashe","Jinx","Varus","Yunara"], blind:true },
  "Nautilus":    { id:"Nautilus", roles:{support:{wr:49.8,pr:10.9,tier:"A"}}, pro:{p:47,wr:48}, flex:["support"], dmg:"mix", a:{cc:3,engage:3,front:2,poke:0,split:0,early:3,late:1,peel:2,wave:0}, counteredBy:["Morgana","Janna","Lulu","Milio"], beats:["Soraka","Nami","Sona","Karma","Yuumi"], syn:["Samira","Kaisa","Xayah","Tristana","Syndra"], blind:true },
  "Rell":        { id:"Rell", roles:{support:{wr:51.8,pr:3.7,tier:"S"}}, pro:{p:12,wr:46}, flex:["support","jungle"], dmg:"ap", a:{cc:3,engage:3,front:2,poke:0,split:0,early:2,late:2,peel:2,wave:0}, counteredBy:["Morgana","Janna","Milio","Lulu"], beats:["Soraka","Nami","Karma","Sona"], syn:["Samira","Kaisa","Yasuo","Katarina","Xayah"], blind:true },
  "Lulu":        { id:"Lulu", roles:{support:{wr:49.7,pr:8.8,tier:"A"}}, pro:{p:23,wr:47}, flex:["support"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:1,split:0,early:2,late:2,peel:3,wave:0}, counteredBy:["Blitzcrank","Pyke","Zyra","Brand"], beats:["Leona","Nautilus","Thresh","Rell"], syn:["Jinx","Vayne","Twitch","Kogmaw","Zeri","Smolder","Yunara"], blind:true },
  "Pyke":        { id:"Pyke", roles:{support:{wr:49.9,pr:6.9,tier:"A"}}, pro:{p:4,wr:48}, flex:["support"], dmg:"ad", a:{cc:2,engage:2,front:0,poke:1,split:0,early:3,late:1,peel:0,wave:0}, counteredBy:["Morgana","Leona","Braum","Taric"], beats:["Soraka","Sona","Janna","Senna","Vel'Koz"], syn:["Samira","MissFortune","Draven"], blind:false },
  "Blitzcrank":  { id:"Blitzcrank", roles:{support:{wr:50.5,pr:5.8,tier:"A"}}, pro:{p:3,wr:47}, flex:["support"], dmg:"mix", a:{cc:3,engage:2,front:1,poke:0,split:0,early:3,late:1,peel:1,wave:0}, counteredBy:["Morgana","Braum","Leona","Taric"], beats:["Soraka","Sona","Seraphine","Lulu","Senna"], syn:["Draven","Jhin","Samira"], blind:false },
  "Soraka":      { id:"Soraka", roles:{support:{wr:50.9,pr:4.8,tier:"A"}}, pro:{p:2,wr:48}, flex:["support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:2,peel:3,wave:0}, counteredBy:["Blitzcrank","Pyke","Leona","Nautilus","Zyra"], beats:["Janna","Sona","Yuumi"], syn:["Nilah","Kogmaw","Twitch","Vayne"], blind:false },
  "Rakan":       { id:"Rakan", roles:{support:{wr:51.3,pr:3.8,tier:"A"}}, pro:{p:13,wr:52}, flex:["support"], dmg:"ap", a:{cc:3,engage:3,front:1,poke:0,split:0,early:2,late:2,peel:2,wave:0}, counteredBy:["Morgana","Janna","Lulu","Braum"], beats:["Soraka","Sona","Karma","Nami"], syn:["Xayah","Kaisa","Yasuo","Orianna"], blind:true },
  "Karma":       { id:"Karma", roles:{support:{wr:49.3,pr:8.4,tier:"B"}}, pro:{p:49,wr:47}, flex:["support","top"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:2,split:0,early:2,late:2,peel:2,wave:1}, counteredBy:["Blitzcrank","Leona","Nautilus","Pyke"], beats:["Sona","Soraka","Yuumi","Braum"], syn:["Ashe","Varus","Ezreal","Sivir","Jayce"], blind:true },
  "Milio":       { id:"Milio", roles:{support:{wr:49.8,pr:6.0,tier:"A"}}, pro:{p:7,wr:50}, flex:["support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:2,peel:3,wave:0}, counteredBy:["Blitzcrank","Pyke","Zyra","Rakan"], beats:["Leona","Nautilus","Rell","Thresh"], syn:["Zeri","Smolder","Kogmaw","Vayne","Yunara","Sivir"], blind:true },
  "Nami":        { id:"Nami", roles:{support:{wr:49.2,pr:8.0,tier:"B"}}, pro:{p:18,wr:49}, flex:["support"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:1,split:0,early:2,late:2,peel:2,wave:0}, counteredBy:["Leona","Nautilus","Blitzcrank","Rell"], beats:["Soraka","Sona","Yuumi","Braum"], syn:["Lucian","Nilah","Ezreal","Jinx"], blind:true },
  "Taric":       { id:"Taric", roles:{support:{wr:52.6,pr:1.2,tier:"S"}}, pro:{p:2,wr:50}, flex:["support"], dmg:"mix", a:{cc:2,engage:1,front:2,poke:0,split:0,early:1,late:3,peel:3,wave:0}, counteredBy:["Zyra","Brand","Morgana","Janna"], beats:["Pyke","Blitzcrank","Leona","Thresh"], syn:["MasterYi","Jinx","Kaisa","Twitch"], blind:true },
  "TahmKench":   { id:"TahmKench", name:"Tahm Kench", roles:{support:{wr:50.9,pr:2.7,tier:"A"},top:{wr:50.6,pr:1.5,tier:"A"}}, pro:{p:5,wr:49}, flex:["support","top"], dmg:"mix", a:{cc:2,engage:1,front:3,poke:0,split:0,early:2,late:2,peel:3,wave:0}, counteredBy:["Morgana","Zyra","Brand","Janna"], beats:["Pyke","Blitzcrank","Leona","Thresh"], syn:["Senna","Vayne","Aphelios","TwistedFate"], blind:true },
  "Janna":       { id:"Janna", roles:{support:{wr:50.5,pr:3.3,tier:"A"}}, pro:{p:3,wr:49}, flex:["support"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:1,split:0,early:2,late:2,peel:3,wave:0}, counteredBy:["Zyra","Brand","Blitzcrank","Pyke"], beats:["Leona","Nautilus","Rell","Thresh","Rakan","Samira"], syn:["Jinx","Vayne","Zeri","Smolder"], blind:true },
  "Zilean":      { id:"Zilean", roles:{support:{wr:50.9,pr:2.6,tier:"A"}}, pro:{p:3,wr:50}, flex:["support","mid"], dmg:"ap", a:{cc:3,engage:0,front:0,poke:1,split:0,early:2,late:3,peel:3,wave:1}, counteredBy:["Blitzcrank","Pyke","Leona","Zyra"], beats:["Soraka","Sona","Braum","Nami"], syn:["Vladimir","Tryndamere","MasterYi","Olaf"], blind:true },
  "Alistar":     { id:"Alistar", roles:{support:{wr:49.9,pr:4.2,tier:"B"}}, pro:{p:16,wr:55}, flex:["support"], dmg:"mix", a:{cc:3,engage:3,front:2,poke:0,split:0,early:2,late:2,peel:2,wave:0}, counteredBy:["Morgana","Janna","Lulu","Milio"], beats:["Soraka","Nami","Karma","Sona"], syn:["Yasuo","Yone","Kaisa","Samira","Tristana"], blind:true },
  "Morgana":     { id:"Morgana", roles:{support:{wr:49.1,pr:4.0,tier:"B"},jungle:{wr:50.0,pr:0.8,tier:"B"}}, pro:{p:4,wr:48}, flex:["support"], dmg:"ap", a:{cc:3,engage:0,front:0,poke:1,split:0,early:2,late:2,peel:3,wave:1}, counteredBy:["Zyra","Brand","Janna","Soraka"], beats:["Thresh","Blitzcrank","Leona","Nautilus","Rell","Pyke"], syn:["Jhin","Caitlyn","Samira","MissFortune"], blind:false },
  "Zyra":        { id:"Zyra", roles:{support:{wr:50.0,pr:2.4,tier:"A"}}, pro:{p:3,wr:49}, flex:["support"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:2,split:0,early:3,late:2,peel:1,wave:1}, counteredBy:["Blitzcrank","Pyke","Leona","Tristana"], beats:["Braum","Taric","Janna","Morgana","TahmKench"], syn:["Jhin","Caitlyn","Ashe"], blind:false },
  "Sona":        { id:"Sona", roles:{support:{wr:49.6,pr:2.6,tier:"B"}}, pro:{p:1,wr:46}, flex:["support"], dmg:"ap", a:{cc:2,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:2,wave:0}, counteredBy:["Blitzcrank","Pyke","Leona","Nautilus","Zyra"], beats:["Janna","Yuumi"], syn:["Lucian","Jinx","Kogmaw"], blind:false },
  "Pantheon":    { id:"Pantheon", roles:{support:{wr:49.7,pr:3.2,tier:"B"},top:{wr:50.0,pr:1.3,tier:"B"},mid:{wr:49.8,pr:0.8,tier:"B"}}, pro:{p:40,wr:49}, flex:["support","top","mid","jungle"], dmg:"ad", a:{cc:2,engage:2,front:1,poke:1,split:0,early:3,late:1,peel:1,wave:1}, counteredBy:["Morgana","Janna","Lulu","Taric"], beats:["Soraka","Nami","Karma","Sona","Seraphine"], syn:["Samira","MissFortune","Taliyah","TwistedFate"], blind:false },
  "Yuumi":       { id:"Yuumi", roles:{support:{wr:49.5,pr:2.2,tier:"B"}}, pro:{p:2,wr:46}, flex:["support"], dmg:"ap", a:{cc:1,engage:0,front:0,poke:1,split:0,early:1,late:3,peel:3,wave:0}, counteredBy:["Blitzcrank","Leona","Nautilus","Pyke"], beats:["Sona","Janna"], syn:["Twitch","Zeri","MasterYi","Sivir"], blind:false },

  // ============ OFF-META / NICHE (full roster coverage) ============
  "Elise":       { id:"Elise", roles:{jungle:{wr:49.6,pr:2.0,tier:"B"}}, pro:{p:4,wr:48}, flex:["jungle"], dmg:"ap", a:{cc:2,engage:2,front:0,poke:1,split:0,early:3,late:1,peel:0,wave:0}, counteredBy:["Warwick","Udyr","RekSai","Rammus"], beats:["Karthus","Kindred","Lillia","Graves"], syn:["LeBlanc","Renekton","Pantheon"], blind:true },
  "Akshan":      { id:"Akshan", roles:{mid:{wr:50.3,pr:1.4,tier:"B"},top:{wr:50.0,pr:0.7,tier:"B"}}, pro:{p:1,wr:48}, flex:["mid","top"], dmg:"ad", a:{cc:0,engage:1,front:0,poke:1,split:2,early:2,late:2,peel:0,wave:1}, counteredBy:["Malzahar","Lissandra","Annie","Yasuo"], beats:["Lux","Xerath","Seraphine","Syndra"], syn:[], blind:false },
  "AurelionSol": { id:"AurelionSol", name:"Aurelion Sol", roles:{mid:{wr:51.0,pr:1.6,tier:"A"}}, pro:{p:2,wr:49}, flex:["mid"], dmg:"ap", a:{cc:2,engage:1,front:0,poke:1,split:0,early:1,late:3,peel:1,wave:3}, counteredBy:["Zed","Yasuo","Fizz","Irelia"], beats:["Galio","Swain","Vladimir","Malzahar"], syn:["JarvanIV","Skarner"], blind:true },
  "Chogath":     { id:"Chogath", name:"Cho'Gath", roles:{top:{wr:50.5,pr:1.6,tier:"B"}}, pro:{p:1,wr:48}, flex:["top"], dmg:"ap", a:{cc:2,engage:1,front:3,poke:1,split:1,early:1,late:3,peel:1,wave:2}, counteredBy:["Vayne","Fiora","Gwen","Darius"], beats:["Malphite","Ornn","Sion","Nasus"], syn:[], blind:true },
  "Fiddlesticks":{ id:"Fiddlesticks", roles:{jungle:{wr:50.8,pr:2.0,tier:"A"}}, pro:{p:2,wr:49}, flex:["jungle"], dmg:"ap", a:{cc:3,engage:2,front:0,poke:0,split:0,early:2,late:2,peel:1,wave:1}, counteredBy:["LeeSin","Nidalee","Shaco","RekSai"], beats:["Zac","Amumu","Sejuani","Nasus"], syn:["Yasuo","Orianna","MissFortune"], blind:true },
  "Gragas":      { id:"Gragas", roles:{top:{wr:50.0,pr:1.5,tier:"B"},jungle:{wr:49.5,pr:1.2,tier:"B"},mid:{wr:49.3,pr:0.5,tier:"B"}}, pro:{p:5,wr:49}, flex:["top","jungle","mid"], dmg:"ap", a:{cc:2,engage:2,front:2,poke:1,split:0,early:2,late:2,peel:2,wave:2}, counteredBy:["Olaf","Irelia","Riven","Darius"], beats:["KSante","Ornn","Sion","Malphite"], syn:["Yasuo","Yone","Orianna"], blind:true },
  "Hecarim":     { id:"Hecarim", roles:{jungle:{wr:49.8,pr:2.5,tier:"B"}}, pro:{p:2,wr:48}, flex:["jungle"], dmg:"ad", a:{cc:2,engage:3,front:1,poke:0,split:1,early:2,late:2,peel:0,wave:1}, counteredBy:["Rammus","Poppy","Trundle","JarvanIV"], beats:["Karthus","Lillia","Kindred","Nidalee"], syn:["Galio","Orianna","TwistedFate"], blind:true },
  "Kalista":     { id:"Kalista", roles:{adc:{wr:47.5,pr:1.0,tier:"B"}}, pro:{p:6,wr:47}, flex:["adc"], dmg:"ad", a:{cc:1,engage:1,front:0,poke:1,split:1,early:3,late:2,peel:1,wave:1}, counteredBy:["Caitlyn","Ziggs","Jhin","Senna"], beats:["Zeri","Smolder","Kogmaw","Aphelios"], syn:["Thresh","Rell","Nautilus","Alistar"], blind:false },
  "Kennen":      { id:"Kennen", roles:{top:{wr:49.8,pr:1.2,tier:"B"},mid:{wr:49.5,pr:0.4,tier:"B"}}, pro:{p:3,wr:49}, flex:["top","mid"], dmg:"ap", a:{cc:3,engage:2,front:0,poke:2,split:1,early:2,late:2,peel:1,wave:2}, counteredBy:["Irelia","Garen","Olaf","Sylas"], beats:["Darius","Sett","Illaoi","Urgot"], syn:["MissFortune","Orianna","Yasuo"], blind:false },
  "Khazix":      { id:"Khazix", name:"Kha'Zix", roles:{jungle:{wr:50.3,pr:5.0,tier:"A"}}, pro:{p:3,wr:48}, flex:["jungle"], dmg:"ad", a:{cc:1,engage:1,front:0,poke:1,split:2,early:2,late:2,peel:0,wave:1}, counteredBy:["Warwick","Vi","Rammus","Trundle"], beats:["Karthus","Kindred","Lillia","Graves"], syn:["TwistedFate","LeBlanc"], blind:true },
  "Kled":        { id:"Kled", roles:{top:{wr:50.6,pr:1.5,tier:"B"}}, pro:{p:1,wr:48}, flex:["top"], dmg:"ad", a:{cc:2,engage:3,front:1,poke:0,split:2,early:3,late:1,peel:0,wave:2}, counteredBy:["Teemo","Vayne","Quinn","Kayle"], beats:["Aatrox","Gnar","Jayce","Renekton"], syn:["MissFortune","Orianna"], blind:false },
  "Maokai":      { id:"Maokai", roles:{support:{wr:50.5,pr:1.8,tier:"A"},jungle:{wr:50.0,pr:1.0,tier:"B"},top:{wr:49.6,pr:0.6,tier:"B"}}, pro:{p:6,wr:50}, flex:["support","jungle","top"], dmg:"ap", a:{cc:3,engage:2,front:3,poke:0,split:0,early:1,late:2,peel:2,wave:1}, counteredBy:["Senna","Karma","Nami","Lillia"], beats:["Blitzcrank","Leona","Rakan","Zac"], syn:["MissFortune","Orianna","Samira"], blind:true },
  "Nunu":        { id:"Nunu", name:"Nunu & Willump", roles:{jungle:{wr:50.6,pr:1.8,tier:"A"}}, pro:{p:1,wr:47}, flex:["jungle"], dmg:"ap", a:{cc:3,engage:2,front:2,poke:0,split:0,early:2,late:1,peel:1,wave:2}, counteredBy:["Lillia","Kindred","Graves","Nidalee"], beats:["Karthus","Belveth","Amumu"], syn:["Yasuo","Galio","TwistedFate"], blind:true },
  "Quinn":       { id:"Quinn", roles:{top:{wr:50.8,pr:0.8,tier:"B"}}, pro:{p:0,wr:48}, flex:["top"], dmg:"ad", a:{cc:1,engage:1,front:0,poke:2,split:3,early:3,late:1,peel:0,wave:1}, counteredBy:["Irelia","Sylas","Trundle","Warwick"], beats:["Darius","Garen","Sett","Olaf","Singed"], syn:["TwistedFate"], blind:false },
  "Renata":      { id:"Renata", name:"Renata Glasc", roles:{support:{wr:50.2,pr:1.5,tier:"B"}}, pro:{p:5,wr:51}, flex:["support"], dmg:"ap", a:{cc:3,engage:1,front:0,poke:1,split:0,early:1,late:3,peel:3,wave:0}, counteredBy:["Blitzcrank","Pyke","Leona","Rell"], beats:["Soraka","Sona","Yuumi","Janna"], syn:["Jinx","Kogmaw","Twitch","Aphelios"], blind:true },
  "Rengar":      { id:"Rengar", roles:{jungle:{wr:50.0,pr:3.0,tier:"B"},top:{wr:49.4,pr:0.5,tier:"B"}}, pro:{p:1,wr:47}, flex:["jungle"], dmg:"ad", a:{cc:1,engage:2,front:0,poke:0,split:2,early:2,late:2,peel:0,wave:1}, counteredBy:["Warwick","Rammus","Vi","JarvanIV"], beats:["Karthus","Lillia","Kindred","Graves"], syn:["LeBlanc","TwistedFate"], blind:false },
  "Sejuani":     { id:"Sejuani", roles:{jungle:{wr:49.5,pr:1.5,tier:"B"}}, pro:{p:6,wr:50}, flex:["jungle"], dmg:"mix", a:{cc:3,engage:3,front:3,poke:0,split:0,early:1,late:2,peel:2,wave:1}, counteredBy:["Lillia","Kindred","Graves","Fiddlesticks"], beats:["Belveth","MasterYi","Briar","Kayn"], syn:["Orianna","Yasuo","MissFortune"], blind:true },
  "Trundle":     { id:"Trundle", roles:{jungle:{wr:50.4,pr:1.2,tier:"B"},top:{wr:50.2,pr:0.8,tier:"B"}}, pro:{p:2,wr:49}, flex:["jungle","top"], dmg:"ad", a:{cc:1,engage:1,front:2,poke:0,split:3,early:2,late:2,peel:1,wave:1}, counteredBy:["Kindred","Lillia","Vayne","Teemo"], beats:["Zac","Sejuani","Skarner","Ornn","KSante"], syn:[], blind:true },
  "Volibear":    { id:"Volibear", roles:{top:{wr:50.3,pr:2.0,tier:"B"},jungle:{wr:49.8,pr:1.5,tier:"B"}}, pro:{p:2,wr:48}, flex:["top","jungle"], dmg:"mix", a:{cc:2,engage:2,front:2,poke:0,split:2,early:2,late:1,peel:0,wave:1}, counteredBy:["Vayne","Quinn","Gnar","Fiora"], beats:["Sion","Nasus","Teemo","Kennen"], syn:[], blind:true },
};

// Remove placeholder nulls
Object.keys(CHAMPIONS).forEach(k => { if (!CHAMPIONS[k]) delete CHAMPIONS[k]; });

// Pro/meta context shown in UI and used by the engine
const META = {
  // 2026 First Selection rules: side choice and pick order are decoupled in pro.
  // Standard tournament draft: first-pick team bans first each phase.
  sideNotes: "2026 pro rules (First Selection) decouple side from pick order. Blue side won ~56% in recent LPL playoffs; LCK skewed red. If your league uses standard tournament draft, blue = first pick.",
  // Champions just changed in 26.12 — engine nudges these
  patchBuffs: ["Aatrox","Gwen","Hwei","Jax","Sylas","Syndra","Tristana","Yuumi"],
  patchNerfs: ["LeeSin","Nocturne","Orianna","Ryze","Varus","XinZhao"],
  // High pro-priority first pick/ban targets (presence ≥ ~40%)
  firstPickBan: ["Orianna","Varus","Rumble","JarvanIV","Karma","Ryze","Nautilus","Ambessa","Pantheon","Nocturne"],
};

/* ================= Flex Queue team =================
   Built from the 5 OP.GG profiles (mastery + most-played, June 2026).
   pool entries: comfort 3 = mastery main / one-trick-level,
   2 = played in pool, 1 = similar-playstyle suggestion (not on their account
   but fits how they play). `like` notes which of their champs it resembles.
   One player per role (a clean 5-stack), but each pool gives in-role options. */
const PLAYERS = [
  { name:"Teemoboy", ign:"Teemoboy2011#Smile", rank:"Diamond 2", role:"jungle",
    pool:[
      {key:"Graves", comfort:3}, {key:"Elise", comfort:3}, {key:"Kindred", comfort:3}, {key:"Hecarim", comfort:3},
      {key:"Khazix", comfort:1, like:"Graves/Kindred carry"}, {key:"Nidalee", comfort:1, like:"Elise"},
      {key:"LeeSin", comfort:1, like:"skirmish tempo"}, {key:"Viego", comfort:1, like:"skirmisher"},
      {key:"Kayn", comfort:1, like:"Hecarim"},
    ] },
  { name:"TheDrunkOfRivia", ign:"TheDrunkOfRivia#NA1", rank:"Emerald 2", role:"top",
    pool:[
      {key:"Shen", comfort:3}, {key:"Zac", comfort:2}, {key:"Sejuani", comfort:2, alt:"jungle"}, {key:"Nautilus", comfort:2, alt:"support"},
      {key:"Ornn", comfort:1, like:"tank top"}, {key:"Sion", comfort:1, like:"tank top"}, {key:"Malphite", comfort:1, like:"tank top"},
      {key:"KSante", comfort:1, like:"tank top"}, {key:"Maokai", comfort:1, like:"tank"}, {key:"Chogath", comfort:1, like:"tank top"},
    ] },
  { name:"StyIebender", ign:"StyIebender#NA1", rank:"Platinum 3", role:"mid",
    pool:[
      {key:"Ahri", comfort:3}, {key:"Lux", comfort:3}, {key:"Gragas", comfort:2}, {key:"Gangplank", comfort:3, alt:"top"},
      {key:"Syndra", comfort:1, like:"control mage"}, {key:"Orianna", comfort:1, like:"control mage"},
      {key:"TwistedFate", comfort:1, like:"roaming mage"}, {key:"Viktor", comfort:1, like:"control mage"}, {key:"Vladimir", comfort:1, like:"Gragas-style"},
    ] },
  { name:"MonkeyDAdam", ign:"MonkeyDAdam#NA1", rank:"Platinum 3", role:"adc",
    pool:[
      {key:"MissFortune", comfort:3}, {key:"Lucian", comfort:3}, {key:"Jinx", comfort:3}, {key:"Syndra", comfort:2, alt:"mid"}, {key:"Ekko", comfort:2, alt:"mid"},
      {key:"Caitlyn", comfort:1, like:"lane bully"}, {key:"Samira", comfort:1, like:"aggressive carry"},
      {key:"Jhin", comfort:1, like:"MF-style"}, {key:"Ashe", comfort:1, like:"utility ADC"}, {key:"Tristana", comfort:1, like:"Lucian tempo"},
    ] },
  { name:"YoitsSam", ign:"YoitsSam#NA1", rank:"Platinum 4", role:"support",
    pool:[
      {key:"Thresh", comfort:3}, {key:"Nautilus", comfort:3}, {key:"Leona", comfort:3}, {key:"Rakan", comfort:2},
      {key:"Alistar", comfort:1, like:"engage"}, {key:"Rell", comfort:1, like:"engage"},
      {key:"Blitzcrank", comfort:1, like:"playmaker"}, {key:"Pyke", comfort:1, like:"roam/engage"},
    ] },
];
const PLAYER_BY_ROLE = { jungle:0, top:1, mid:2, adc:3, support:4 };
